name: Test PRs for info page

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'info_page/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Build info.yukkuricraft.net
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@master

    - name: Yarn Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd info_page install
    - name: Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd info_page build

    - name: Yarn Test
      run: echo "Where my tests at @katrix? :P"
